/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface TodoModel {
  title: string
  completed?: boolean
  id?: string
  createdAt?: string
  updatedAt?: string
  version?: number
}
export interface TodoModel {
  id?: string
  title: string
  completed?: boolean
  createdAt?: string
  updatedAt?: string
  version?: number
}
export type JsTodo = Todo
export declare class Todo {
  constructor()
  get(id: string): TodoModel
  list(): Array<TodoModel>
  add(title: string, completed?: boolean | undefined | null): TodoModel
  edit(id: string, title: string, completed?: boolean | undefined | null): TodoModel
  delete(id: string): void
}
export type JsCoreSDK = CoreSdk
export declare class CoreSdk {
  constructor()
  get todo(): Todo
}
